import type { MenuItem, Testimonial, Promo } from "@/types";

export const menuItems: MenuItem[] = [
  {
    id: "1",
    name: "NaksBite Classic",
    description: "Double beef patty, cheddar cheese, lettuce, tomato, special sauce",
    price: 650,
    category: "Burgers",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    popular: true,
  },
  {
    id: "2",
    name: "Spicy Inferno",
    description: "Beef patty, pepper jack cheese, jalapeños, spicy mayo, chipotle sauce",
    price: 750,
    category: "Burgers",
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop",
    popular: true,
    spicy: true,
  },
  {
    id: "3",
    name: "BBQ Smokehouse",
    description: "Beef patty, smoked gouda, crispy onions, BBQ sauce, bacon",
    price: 800,
    category: "Burgers",
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=400&h=300&fit=crop",
    popular: true,
  },
  {
    id: "4",
    name: "Veggie Delight",
    description: "Plant-based patty, vegan cheese, avocado, sprouts, garlic aioli",
    price: 550,
    category: "Burgers",
    image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400&h=300&fit=crop",
    vegetarian: true,
  },
  {
    id: "5",
    name: "Mushroom Swiss",
    description: "Beef patty, Swiss cheese, sautéed mushrooms, truffle mayo",
    price: 700,
    category: "Burgers",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop",
  },
  {
    id: "6",
    name: "Chicken Crisp",
    description: "Crispy chicken breast, coleslaw, pickles, honey mustard",
    price: 600,
    category: "Chicken",
    image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400&h=300&fit=crop",
    popular: true,
  },
  {
    id: "7",
    name: "Loaded Fries",
    description: "Crispy fries topped with cheese sauce, bacon bits, and green onions",
    price: 350,
    category: "Sides",
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop",
    popular: true,
  },
  {
    id: "8",
    name: "Onion Rings",
    description: "Golden fried onion rings with smoky dipping sauce",
    price: 300,
    category: "Sides",
    image: "https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=300&fit=crop",
  },
  {
    id: "9",
    name: "Classic Milkshake",
    description: "Thick and creamy vanilla, chocolate, or strawberry shake",
    price: 400,
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop",
  },
  {
    id: "10",
    name: "Fresh Lemonade",
    description: "Freshly squeezed lemons with a hint of mint",
    price: 250,
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=400&h=300&fit=crop",
  },
  {
    id: "11",
    name: "Chocolate Brownie",
    description: "Warm chocolate brownie with vanilla ice cream",
    price: 350,
    category: "Desserts",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop",
  },
  {
    id: "12",
    name: "Chicken Wings",
    description: "6 pieces of crispy wings with your choice of sauce",
    price: 500,
    category: "Chicken",
    image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400&h=300&fit=crop",
    spicy: true,
  },
];

export const categories = ["All", "Burgers", "Chicken", "Sides", "Drinks", "Desserts"];

export const testimonials: Testimonial[] = [
  {
    name: "Sarah Wanjiku",
    role: "Food Blogger",
    quote: "The NaksBite Classic is hands down the best burger in Nairobi. The beef is perfectly seasoned and the sauce is addictive!",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
  },
  {
    name: "James Otieno",
    role: "Regular Customer",
    quote: "I've tried every burger joint in the city, and nothing comes close to NaksBite. The delivery is always fast and food arrives hot.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
  },
  {
    name: "Amina Hassan",
    role: "Office Worker",
    quote: "Their customizer is genius! I can build my perfect burger every time. The spicy inferno with extra cheese is my go-to.",
    rating: 4,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
  },
];

export const promos: Promo[] = [
  {
    id: "1",
    title: "Monday Madness",
    description: "Buy any burger, get free loaded fries. Perfect way to start your week!",
    code: "MONDAYFREE",
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop",
  },
  {
    id: "2",
    title: "Family Feast",
    description: "Get 4 burgers, 2 sides, and 4 drinks for only KES 2,500. Save KES 500!",
    code: "FAMILY",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop",
  },
  {
    id: "3",
    title: "Student Special",
    description: "15% off your entire order with a valid student ID. Study fuel sorted!",
    code: "STUDENT15",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=300&fit=crop",
  },
  {
    id: "4",
    title: "Weekend Warrior",
    description: "Free delivery on all orders over KES 1,000 every Saturday and Sunday.",
    code: "WEEKEND",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop",
  },
  {
    id: "5",
    title: "Late Night Cravings",
    description: "20% off all orders placed after 10 PM. For the night owls!",
    code: "LATENIGHT",
    image: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=400&h=300&fit=crop",
  },
  {
    id: "6",
    title: "Birthday Bash",
    description: "Get a free dessert with any order during your birthday week. Treat yourself!",
    code: "BIRTHDAY",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=300&fit=crop",
  },
];

export const customizerOptions = {
  patties: [
    { id: "beef", name: "Beef Patty", price: 0, description: "100% Kenyan beef" },
    { id: "double-beef", name: "Double Beef", price: 200, description: "Double the beef, double the flavor" },
    { id: "chicken", name: "Crispy Chicken", price: 0, description: "Crispy fried chicken breast" },
    { id: "veggie", name: "Veggie Patty", price: 0, description: "Plant-based protein" },
  ],
  cheeses: [
    { id: "none", name: "No Cheese", price: 0 },
    { id: "cheddar", name: "Cheddar", price: 50 },
    { id: "swiss", name: "Swiss", price: 60 },
    { id: "pepper-jack", name: "Pepper Jack", price: 60 },
    { id: "gouda", name: "Smoked Gouda", price: 70 },
  ],
  toppings: [
    { id: "lettuce", name: "Lettuce", price: 0 },
    { id: "tomato", name: "Tomato", price: 0 },
    { id: "onions", name: "Onions", price: 0 },
    { id: "pickles", name: "Pickles", price: 0 },
    { id: "jalapenos", name: "Jalapeños", price: 30 },
    { id: "bacon", name: "Bacon", price: 80 },
    { id: "avocado", name: "Avocado", price: 60 },
    { id: "egg", name: "Fried Egg", price: 50 },
    { id: "mushrooms", name: "Mushrooms", price: 40 },
  ],
  sauces: [
    { id: "ketchup", name: "Ketchup", price: 0 },
    { id: "mayo", name: "Mayonnaise", price: 0 },
    { id: "bbq", name: "BBQ Sauce", price: 0 },
    { id: "spicy-mayo", name: "Spicy Mayo", price: 20 },
    { id: "truffle", name: "Truffle Mayo", price: 50 },
    { id: "garlic-aioli", name: "Garlic Aioli", price: 30 },
  ],
  buns: [
    { id: "classic", name: "Classic Bun", price: 0 },
    { id: "brioche", name: "Brioche Bun", price: 30 },
    { id: "whole-wheat", name: "Whole Wheat", price: 20 },
    { id: "gluten-free", name: "Gluten-Free", price: 50 },
  ],
};